services:
  - type: web
    name: image-processor
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
